spring:
  application:
    name: eureka-server
eureka:
  environment: local # 此处设置会改变eureka控制台的显示
  instance:
    #status-page-url: http://localhost:${server.port:8080}/swagger-ui.html
    #lease-renewal-interval-in-seconds: 30 # eureka客户端需要多长时间（以秒为单位）向eureka服务器发送心跳以指示它仍然处于活动状态
    #lease-expiration-duration-in-seconds: 90 # eureka服务器在收到最后一次心跳后等待的时间（以秒为单位），然后它可以从视图中删除此实例
    prefer-ip-address: true # 设置微服务调用地址为IP优先（缺省为false）
    instance-id: ${spring.cloud.client.ip-address}:${server.port:8080} # 注册中心显示的名称IP:端口（缺省${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port:8080}}机器主机名:应用名称:应用端口）
    ip-address: 127.0.0.1
  client:
    #register-with-eureka: true # 设置是否将自己作为客户端注册到注册中心（缺省true,单节点设置成false，集群需要互相同步）
    #fetch-registry: true # 设置是否从注册中心获取注册信息（缺省true,单节点设置成false，集群需要互相同步）
    #prefer-same-zone-eureka: true
    service-url:
      cn-qingdao: http://127.0.0.1:8761/eureka/
      cn-beijing: http://127.0.0.1:8762/eureka/
  server:
    #response-cache-update-interval-ms: 3000
    #response-cache-auto-expiration-in-seconds: 10
    #peer-eureka-nodes-update-interval-ms: 3000
    #renewal-threshold-update-interval-ms: 3000
    #peer-eureka-status-refresh-time-interval-ms: 30000
    #peer-node-total-connections: 1000
    #peer-node-total-connections-per-host: 500
    use-read-only-response-cache: false
    eviction-interval-timer-in-ms: 3000 # 清理未续约节点(evict)周期（缺省为60*1000ms）
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）生产环境需要打开
    peer-node-connect-timeout-ms: 500
    peer-node-read-timeout-ms: 500
    wait-time-in-ms-when-sync-empty: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'