server:
  port: 8762
eureka:
  datacenter: cn-beijing # 此处设置会改变eureka控制台的显示
  instance:
    metadata-map.zone: cn-beijing
  client:
    region: cn
    availability-zones:
      cn: cn-beijing,cn-qingdao
  server:
    my-url: http://127.0.0.1:8762/eureka/